AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resume API using Lambda and DynamoDB

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128

Resources:
  ResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: Resume
      Events:
        ResumeApi:
          Type: Api
          Properties:
            Path: /resume
            Method: get

  ResumeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Resume
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
